# -*- coding: utf-8 -*-
"""Visualization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F3pn-aPmVUE5xnpg-M5krQnrw2hw9gYH
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

data_frame = pd.read_csv("/content/drive/MyDrive/Datasets/API_EN.ATM.GHGT.KT.CE_DS2_en_csv_v2_5358514.csv")
data_frame.head()

data_frame['Country Name'].unique()

countries= data_frame[["Country Name","1975","1985","1995","2005","2015"]]

countries = countries[countries["Country Name"].isin(["India","Australia","France","Pakistan","Bangladesh","United States","China","Nigeria","Spain","South Africa","Indonesia","Russian Federation","Japan"])]

countries

plt.figure(figsize=(20,10))
figure,ax = plt.subplots(figsize=(20,10))
x=np.arange(len(countries))
width=0.1
bar1 = ax.bar(x-width*2,countries["1975"],width,color="g")
bar2 = ax.bar(x-width,countries["1985"],width,color="b")
bar3 = ax.bar(x,countries["1995"],width,color="r")
bar4 = ax.bar(x+width,countries["2005"],width,color="y")
bar5 = ax.bar(x+width*2,countries["2015"],width,color='orange')
plt.xticks(x+width,countries['Country Name'])
'''plt.bar(countries["Country Name"],countries["2015"],label="2015",color="red")
plt.bar(countries["Country Name"],countries["2016"],label="2016",color="blue")
plt.bar(countries["Country Name"],countries["2017"],label="2017",color="green")
plt.bar(countries["Country Name"],countries["2018"],label="2018",color="purple")
plt.bar(countries["Country Name"],countries["2019"],label="2019",color="orange")'''
plt.xlabel('Countries')
plt.ylabel('Green house emission')
plt.title('Green house emission of countries from 1975 to 2015')
ax.legend((bar1,bar2,bar3,bar4,bar5),('1975','1985','1995','2005','2015'))
plt.show()

"""Green house emission has been tremendously increasing in both China and India as population of both the countries is high and usage of vehicles is also more over the decades in both the countries. Next populated country is United States and emission of green house is also been increasing over the decades."""

data_frame = pd.read_csv("/content/drive/MyDrive/Datasets/API_SP.POP.TOTL_DS2_en_csv_v2_5358404.csv",skiprows=4)
data_frame.head()
countries= data_frame[["Country Name","1975","1985","1995","2005","2015"]]
countries = countries[countries["Country Name"].isin(["India","Australia","France","Pakistan","Bangladesh","United States","China","Nigeria","Spain","South Africa","Indonesia","Russian Federation","Japan"])]



figure,ax = plt.subplots(figsize=(20,10))
x=np.arange(len(countries))
width=0.1
bar1 = ax.bar(x-width*2,countries["1975"],width,color="g")
bar2 = ax.bar(x-width,countries["1985"],width,color="b")
bar3 = ax.bar(x,countries["1995"],width,color="r")
bar4 = ax.bar(x+width,countries["2005"],width,color="y")
bar5 = ax.bar(x+width*2,countries["2015"],width,color='orange')
plt.xticks(x+width,countries['Country Name'])
plt.xlabel('Countries')
plt.ylabel('Population')
plt.title('Population of countries from 1975 to 2015')
ax.legend((bar1,bar2,bar3,bar4,bar5),('1975','1985','1995','2005','2015'))

plt.show()

"""As China and India has more rivers and more areable land which is the reason for increase in population as compared to other countries. Also these two are never effected with natural and human calamities which results in population sustainity."""

data_frame_land = pd.read_csv("/content/drive/MyDrive/Datasets/API_AG.LND.FRST.K2_DS2_en_csv_v2_5362273.csv",skiprows=4)
data_frame_land.head()
countries_forest= data_frame[["Country Name","1975","1985","1995","2005","2015"]]
years=['1975','1985','1995','2005','2015']
countries_forest = countries[countries["Country Name"].isin(["India","Australia","France","Pakistan","Bangladesh","United States","China","Nigeria","Spain","South Africa","Indonesia","Russian Federation","Japan"])]

countries_forest[countries_forest["Country Name"]=="India"].iloc[:,1:].values[0].tolist()

countries_forest["Country Name"].values.tolist()

figure,ax = plt.subplots(figsize=(20,10))
# pd.crosstab(0years,countries_forest['Country Name']).plot()
count = countries_forest["Country Name"].values.tolist()
l=[]
colors=["b","g","r","c","m","y","k","orange","purple","pink","brown","violet","indigo"]
for i,c in enumerate(count):

  ax.plot(years,countries_forest[countries_forest["Country Name"]==c].iloc[:,1:].values[0].tolist(),color=colors[i],label=c)
ax.legend(count)

plt.xlabel("Years")
plt.ylabel("Forest Land")
plt.title("Forest land of countries over the decades")

plt.show()

"""As Area of land is more,the wild life habitant is highly concentrated in China and India over the decades and most unused land has been converted for wild life."""

data_frame_land = pd.read_excel("/content/drive/MyDrive/Datasets/Bangladesh.csv.xlsx")
data_frame_land.head()

data_frame_land.drop(["Country Name","Country Code","Indicator Code"],axis=1,inplace=True)

data_frame_land = data_frame_land.transpose()

data_frame_land.columns = data_frame_land.iloc[0]

data_frame_land= data_frame_land.iloc[1:,:]

data_frame_land

data_frame_land.fillna(0,inplace=True)

data_frame_land=data_frame_land.astype('float')

import seaborn as sns

corrlearion = data_frame_land.corr()

sns.heatmap(corrlearion,annot=True)

"""Bangladesh is located at south Asia and resultant areas for more emission of CO2 are:
1.Solid fuel Consumption
2.Gaseous fuel consumption
3.Liquid fuel consumption
4.Intensity of oil equivalent energy usage.
"""

indian_data = pd.read_excel("/content/drive/MyDrive/Datasets/India.xlsx")
indian_data.head()

indian_data.drop(["Country Name","Country Code","Indicator Code"],axis=1,inplace=True)
indian_data = indian_data.transpose()
indian_data.columns = indian_data.iloc[0]
indian_data= indian_data.iloc[1:,:]
indian_data.fillna(0,inplace=True)
indian_data=indian_data.astype('float')

import seaborn as sns

corrlearion = indian_data.corr()

sns.heatmap(corrlearion,annot=True)

"""As India is a densily populated country the reasons for increasing urban population are:
1.Development is also happening as equal to rural areas.
2.People are tend to live comfortably compared to rural areas as opportunties are increasing.
"""